# Base image with Python 3.10 and CPU-only support
FROM python:3.10-slim

# Environment setup
ENV PYTHONUNBUFFERED=1 \
    TRANSFORMERS_CACHE=/models/cache \
    HF_HUB_OFFLINE=1

# Set working directory
WORKDIR /app


RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libgl1-mesa-glx \
    poppler-utils \
    git \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

COPY . .


VOLUME ["/app/output_json"]

# Run your main script
CMD ["python", "train.py"]
