# Base image
FROM python:3.10-slim

# Environment variables
ENV PYTHONUNBUFFERED=1 \
    TRANSFORMERS_CACHE=/models/cache \
    HF_HUB_OFFLINE=1

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libgl1-mesa-glx \
    poppler-utils \
    git \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all source code
COPY . .

CMD ["python", "train.py"]
